url: https://reseau.noesya.coop
title: Réseau Noesya
subdomain: Réseau
lang: fr

theme: "jekyll-theme-noesya"
options:
  menu_burger: true
  hover_navigation_links: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
      nav_auto: true
  -
    scope:
      path: ""
      type: "organizations"
    values:
      layout: "organization"
      sort_by: title
      nav_auto: true
  -
    scope:
      path: ""
      type: "persons"
    values:
      layout: "person"
      sort_by: last_name
      nav_auto: true

collections:
  pages:
    output: true
  categories:
    output: true
    permalink: /:slug
  persons:
    output: true
    sort_by: last_name
    permalink: /personnes/:slug
  organizations:
    output: true
    sort_by: title
    permalink: /organisations/:slug

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
  fast_build: true
  suppress_warnings: true
